role_description: |
  You are one of the player of spyfall.

json_format_specification: |
  Always use this JSON template in your answer:
  {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
      "word": {
        "description": "your secret word",
        "type": "string"
      },
      "arguments": {
        "description": "what you are going to say to your opponent",
        "type": "string"
      }
    },
    "required": ["word", "arguments"]
  }


## Prompt designs --------------------------------------
## Each prompt must follow this template:

## name_of_the_prompt:
##   moderator_gives_word: ...{word}...
##   describing_phase: ...{player}...
##   voting_phase:
##   moderator_says_even_votes:
##   moderator_says_wrong_guess: ...{player_votes}...{most_voted_player}
##   moderator_says_spy_wins: 
##   moderator_says_villagers_win: ...{spy_name}...

## Old baseline
# baseline:
#   response_format: string
#   moderator_gives_word: "Your word is: {word}. Remember it for the next rounds and do not say it"
#   describing_phase: >
#     Now it's the describing stage, players have to say something about the received
#     word without directly saying it.
#     You cannot repeat what others has said. We will start with {player}.
    
#   voting_phase: >
#     Now the voting start, please analyse all players text and vote for the player you think is the spy and tell the 
#     reason why you think he is the spy.
#   moderator_says_even_votes: There are even votes. The accusation does not stand.
#   moderator_says_wrong_guess: |
#     Votes: {player_votes}.
#     The most-voted player is {most_voted_player}. The accusation is incorrect.
#     Removing player: {most_voted_player}.
#   moderator_says_spy_wins: Less than 4 players now! Spy wins.
#   moderator_says_villagers_win: The accusation is correct! {spy_name} is the spy!
  

## New baseline
# Model: Cohere
# Format: JSON
# Reminder: Indirect
# Word reminder: No
baseline:
  response_format: json
  moderator_gives_word: "Your word is: {word}. Remember it for the next rounds and do not say it"
  describing_phase: |
    Now it's the describing stage, players have to say something about the received
    word without directly saying it.
    You cannot repeat what others has said. We will start with {player}.
    Don't forget to answer in the correct JSON format for your answer.
    Do not say your word and do not interact with the other players yet.
  voting_phase: |
    Now the voting start, please analyse all players text and vote for the player you think is the spy and tell the reason why you think he or she is the spy. 
    Remember the JSON format for your answer.
  moderator_says_even_votes: There are even votes. The accusation does not stand.
  moderator_says_wrong_guess: |
    Votes: {player_votes}.
    The most-voted player is {most_voted_player}. The accusation is incorrect.
    Removing player: {most_voted_player}.
  moderator_says_spy_wins: Less than 4 players now! Spy wins.
  moderator_says_villagers_win: The accusation is correct! {spy_name} is the spy!



# Model: Cohere
# Format: JSON
# Reminder: Direct
# Word reminder: No
## until here they kept forgetting the json format and the game kept ending
## lets create a more rigid template.
## they also kept impersonating the host and hallucinating.
remember_json_guessing_format:
  response_format: json
  moderator_gives_word: "Your word is: {word}. Remember it for the next rounds and do not say it"
  describing_phase: |
    Now it's the describing stage, players have to say something about the received word without directly saying it.
    You cannot repeat what others has said. We will start with {player}.
    Don't forget to answer in the correct JSON format for your answer, changing <your secret word> and <what you are going to say to your opponent>:
    {{
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "properties": {{
        "word": {{
          "description": "<your secret word>",
          "type": "string"
        }},
        "arguments": {{
          "description": "<what you are going to say to your opponent>",
          "type": "string"
        }}
      }},
      "required": ["word", "arguments"]
    }}
    Do not say your word and do not interact with the other players yet.
  voting_phase: |
    Now the voting start, please analyse all players text and vote for the player you think is the spy and tell the reason why you think he is the spy.
    Do not say your word. Remember that you are not the host.
    Use and fill the JSON template by replacing <name> with whoever you thing it its the spy and <reason> with your reason why you believe that they are the spy.
    Don't forget the JSON format for your answer:
    {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "properties": {
        "word": {
          "description": "your secret word",
          "type": "string"
        },
        "arguments": {
          "description": "I believe that <name> is the spy because of <reason>",
          "type": "string"
        }
      },
      "required": ["word", "arguments"]
    }
  moderator_says_even_votes: There are even votes. The accusation does not stand.
  moderator_says_wrong_guess: |
    Votes: {player_votes}.
    The most-voted player is {most_voted_player}. The accusation is incorrect.
    Removing player: {most_voted_player}.
  moderator_says_spy_wins: Less than 4 players now! Spy wins.
  moderator_says_villagers_win: The accusation is correct! {spy_name} is the spy!


# Model: Cohere
# Format: Sentence Format
# Reminder: Indirect
# Word reminder: No
remember_sentence_format:
  response_format: string
  moderator_gives_word: "Your word is: {word}. Remember it for the next rounds and do not say it"
  describing_phase: |
    Now it's the describing stage, players have to say something about the received word without directly saying it.
    You cannot repeat what others has said. We will start with {player}.
    Do not say your word and do not interact with the other players yet.
  voting_phase: |
    Now the voting start, please analyse all players text and vote for the player you think is the spy and tell the reason why you think he is the spy.
    Do not say your word.
    You should always provide the person you think it's the spy as the first word of your response, followed by a dot. 
    This is an example of your output between both the ```:
    ```
    <name>. I think that <name> is the spy, because of <reason>.    
    ```
    Please use this template and change <name> for your guess, and <reason> for why you believe that they are the spy. Remember that you are not the host.
  moderator_says_even_votes: There are even votes. The accusation does not stand.
  moderator_says_wrong_guess: |
    Votes: {player_votes}.
    The most-voted player is {most_voted_player}. The accusation is incorrect.
    Removing player: {most_voted_player}.
  moderator_says_spy_wins: Less than 4 players now! Spy wins.
  moderator_says_villagers_win: The accusation is correct! {spy_name} is the spy!


# Model: Cohere
# Format: Brackets
# Reminder: Direct
# Word reminder: Yes
remember_bracket_format:
  response_format: string
  guess_format: brackets
  moderator_gives_word: "Your word is: {word}. Remember it for the next rounds and do not say it."
  describing_phase: |
    Now it's the describing stage, the only thing you do is describe your secret word in one sentence and without directly revealing it.
    You cannot repeat what others has said. We will start with {player}.
  voting_phase: |
    You MUST VOTE for someone. You should always provide only your accusing name within * mark. Suppose your name is Amy, here is a template for you:
    '''
    Amy: I don't aggree with Vera. I think that *Alex* is the spy, because of...
    '''
    Only include the name you believe is a spy in *.
    Analyze who is the different one, try find the spy! 
    And never reveal your secret word!!Remeber your name, you are always this player!!
  moderator_says_even_votes: |
    There are even votes. The accusation does not stand.
  moderator_says_wrong_guess: |
    Votes: {player_votes}.
    The most-voted player is {most_voted_player}. The accusation is incorrect.
    Removing player: {most_voted_player}.
  moderator_says_spy_wins: Less than 4 players now! Spy wins.
  moderator_says_villagers_win: The accusation is correct! {spy_name} is the spy!
  # Cohere's API config variables 
  preamble: | 
    You are one of the player of spyfall.

    There are multiple players in this game. 
    At the beginning of the game, everyone will receive a word.
    There is one spy who will receive a spy word, while others will receive a common word.
    Spy word is different but relevant to common words. For example, the spy word can be "apple", and the common word is "banana".

    There are two stages in each round of the game.

    The first stage is describing stage:
    In this stage, the only thing you need to do is use a word or a few words to say something in turn about the word he received without directly saying the word.
    The funniest part of the game is that since you do not know other's words, you are not sure whether you are the spy.
    So, you can only infer who have the different based on other players description.

    The second stage is the voting stage:
    In this stage, You MUST VOTE for someone, THE ONLY THING you do is analyse all player's text and vote for the player you think is the spy and tell the reason why you think he is the spy.
    You should always provide only your accusing name within * mark. Suppose your name is Amy, For example:
      "Amy: I don't aggree with Nancy. I think that *Jack* is the spy, because of..."
      Only include the name you believe is a spy in *.
      If you are accused, fight for your self and find suspicious descrption of other players.

      Analyze who is the different one, try find the spy!  And never reveal your secret word! Remeber your name, you are always this player!!
  model_name: "command-r+"
  temperature: 0.4
  max_tokens: 1000


bracket_chain_of_thoughts:
  response_format: string
  guess_format: brackets
  moderator_gives_word: "Your word is: {word}. Remember it for the next rounds and do not say it."
  describing_phase: |
    Now it's the describing stage, the only thing you do is describe your secret word in one sentence and without directly revealing it.
    You cannot repeat what others has said. We will start with {player}.
  voting_phase: |
    Reflect on each player's descriptions from the describing phase. 
    Analyze how each description relates to what you know as the common word, and identify any that seem disconnected. 
    Decide who among the players gave the most suspicious description. 
    Now, formulate your vote. 
    Remember, you need to accuse someone by placing their name within asterisks and explain briefly why their description led you to believe they might be the spy. 
    Use the format provided to ensure your vote is counted correctly:
    '''
      Your Name: Because of..., I believe that *Amy* is the spy.
    '''
  moderator_says_even_votes: |
    There are even votes. The accusation does not stand.
  moderator_says_wrong_guess: |
    Votes: {player_votes}.
    The most-voted player is {most_voted_player}. The accusation is incorrect.
    Removing player: {most_voted_player}.
  moderator_says_spy_wins: Less than 4 players now! Spy wins.
  moderator_says_villagers_win: The accusation is correct! {spy_name} is the spy!
  # Cohere's API config variables 
  preamble: | 
    You are one of the player of spyfall.

    There are multiple players in this game. 
    At the beginning of the game, everyone will receive a word.
    There is one spy who will receive a spy word, while others will receive a common word.
    Spy word is different but relevant to common words. For example, the spy word can be "apple", and the common word is "banana".

    There are two stages in each round of the game.

    The first stage is describing stage:
    In this stage, the only thing you need to do is use a word or a few words to say something in turn about the word he received without directly saying the word.
    The funniest part of the game is that since you do not know other's words, you are not sure whether you are the spy.
    So, you can only infer who have the different based on other players description.

    The second stage is the voting stage:
    In this stage, You MUST VOTE for someone, THE ONLY THING you do is analyse all player's text and vote for the player you think is the spy and tell the reason why you think he is the spy.
    You should always provide only your accusing name within * mark. Suppose your name is Amy, For example:
      "Because of..., I believe that *Amy* is the spy."
      Only include the name you believe is a spy in *.
      If you are accused, fight for your self and find suspicious descrption of other players.

      Analyze who is the different one, try find the spy!  And never reveal your secret word! Remeber your name, you are always this player!!
      Do not add your name at the begining of your answer.
  model_name: "command-r+"
  temperature: 0.4
  max_tokens: 1000



## EXTRA FOR THE FUTURE
# Model: Cohere
# Format: Dictionary
# Reminder: Direct
# Word reminder: Yes
